FROM      busybox

######## INSTALL JAVA #################
#ADD JAVA REPO
#
COPY  jre1.8.0_25 jre1.8.0_25
RUN   ln -s jre1.8.0_25 java
ENV   PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/x86_64-cros-linux-gnu/gcc-bin/4.6.3:/java/bin


####### END JAVA INSTALL ##############
